// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_UfRz1qT5rePEMSS7zGkDKej5eTL1Tg',
    appId: '1:307915937238:web:d31361c563548acf7b0077',
    messagingSenderId: '307915937238',
    projectId: 'briqko-agents',
    authDomain: 'briqko-agents.firebaseapp.com',
    storageBucket: 'briqko-agents.firebasestorage.app',
    measurementId: 'G-DGFZHFBDYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbTag52vCbKR1ncF8qtJIt9k4nMxLG6k',
    appId: '1:307915937238:android:6941d677d82a4d087b0077',
    messagingSenderId: '307915937238',
    projectId: 'briqko-agents',
    storageBucket: 'briqko-agents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFiNZdhLS42-I2e2BPA2NNFAy3BEWsyzI',
    appId: '1:307915937238:ios:22e34ba6b99db5f77b0077',
    messagingSenderId: '307915937238',
    projectId: 'briqko-agents',
    storageBucket: 'briqko-agents.firebasestorage.app',
    iosBundleId: 'com.example.acn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFiNZdhLS42-I2e2BPA2NNFAy3BEWsyzI',
    appId: '1:307915937238:ios:22e34ba6b99db5f77b0077',
    messagingSenderId: '307915937238',
    projectId: 'briqko-agents',
    storageBucket: 'briqko-agents.firebasestorage.app',
    iosBundleId: 'com.example.acn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_UfRz1qT5rePEMSS7zGkDKej5eTL1Tg',
    appId: '1:307915937238:web:fb8e941d6350c3897b0077',
    messagingSenderId: '307915937238',
    projectId: 'briqko-agents',
    authDomain: 'briqko-agents.firebaseapp.com',
    storageBucket: 'briqko-agents.firebasestorage.app',
    measurementId: 'G-FBHJVPPWVZ',
  );
}
